[package]
name = "molten"
version = "0.1.0"
authors = ["transistor <trans@jabberwocky.ca>"]

[dependencies]
#nom = "^3.2"
nom = { version = "^3.2", features = ["verbose-errors"] }
nom_locate = "^0.1"
clap = "^2"
llvm-sys = "50"

